blank_issues_enabled: false
contact_links:
  - name: 🤔 Have questions or need support?
    url: https://discord.gg/WzhxEY62mB
    about: Discuss with us on Discord
  - name: 🤔 Have questions or need support?
    url: https://github.com/helgeerbe/OpenDTU-OnBattery/discussions
    about: Use the GitHub Discussions feature